# Generated by Django 4.2.16 on 2024-11-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aroma', models.FloatField()),
                ('flavor', models.FloatField()),
                ('color', models.FloatField()),
                ('texture', models.FloatField()),
                ('overall_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SensoryEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(max_length=100)),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beer')),
            ],
        ),
    ]
