# Generated by Django 4.2.16 on 2024-11-23 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_beer_sensoryevaluation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cerveza',
        ),
    ]
