# Generated by Django 4.2.16 on 2024-11-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_cerveza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensoryevaluation',
            name='beer',
        ),
    ]
